### ISSUE TITLE
请教下怎么把它部署到服务器上？

### ISSUE THREAD

**Issue by GeekHowl** [youzhengjie9/yblog#4]

**Comment by youzhengjie9** [comment]
请问您是哪一步不会了呢？readme有部署的步骤，如果还是不行就问我吧

**Comment by howl1992** [comment]
我是个新手菜鸟 我看需要使用docker，这个东西我还没学 我先去学学怎么安装

**Comment by youzhengjie9** [comment]
docker部署也可以，如果你不会docker没关系，可以用windows的部署方式，readme文档也有写😊
